name: CI-CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Check HTML File
        run: |
          test -f index.html

      - name: CI/CD Success
        run: echo "CI/CD Pipeline completed successfully"
